### ISSUE TITLE
DHT11 Sensor Returns double 0.0. ErrorCount = 0

### ISSUE THREAD

**Issue by burakilk** [MarcWoodyard/Raspberry-Pi-Climate-Control#2]
I have a problem, the DHT11 sensor always returns double 0.0 . ErrorCount = 0

**Comment by MarcWoodyard** [comment]
Hi burakilk,

Did you modify the dht11.java file in any way?

Also are you reading the values in a loop until you get a valid result?

https://stackoverflow.com/questions/28486159/read-temperature-from-dht11-using-pi4j/34976602#comment73440997_34976602

**Comment by MarcWoodyard** [comment]
I believe I found the issue. In Controller.java on line 59, it specifies the GPIO pin number that the DHT11 temperature sensor is plugged into. If you change that number to the pin number your DHT11 sensor is plugged into, it should work. 

`this.tempSensor.updateTemperature(7);`

https://github.com/MarcWoodyard/Raspberry-Pi-Climate-Control/blob/master/src/Controller.java#L59

I'll make this a command line option rather than hard code the pin number in a future update.

**Comment by MarcWoodyard** [comment]
You can now specify the GPIO pin in the DHT11Config.txt file.

https://github.com/MarcWoodyard/Raspberry-Pi-Climate-Control/blob/master/src/Config/DHT11Config.txt
